name: Deploy to R2
on:
  push:
    branches: [main]

jobs:
  deploy:
    uses: Gigi-Pizza/ci-workflows/.github/workflows/deploy.yml@main
    with:
      bucket_name: gigi-assets
      build_command: "npm run build"
      build_dir: "build"
    secrets:
      CLOUDFLARE_GIGI_API_TOKEN: ${{ secrets.CLOUDFLARE_GIGI_API_TOKEN }}
      CLOUDFLARE_GIGI_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_GIGI_ACCOUNT_ID }}
